# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       pkgconfig

# >> macros
# << macros

Summary:    A tool for determining compilation options
Version:    0.27.1
Release:    1
Group:      Development/Tools
License:    GPLv2+
URL:        http://pkgconfig.freedesktop.org
Source0:    http://www.freedesktop.org/software/pkgconfig/releases/pkg-config-%{version}.tar.gz
Source100:  pkgconfig.yaml
Patch0:     pkgconfig-aarch64.patch
Provides:   pkgconfig(pkg-config) = %{version}

%description
The pkgconfig tool determines compilation options. For each required
library, it reads the configuration file and outputs the necessary
compiler and linker flags.



%prep
%setup -q -n pkg-config-%{version}
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --disable-shared \
    --with-internal-glib \
    --with-pc-path=%{_libdir}/pkgconfig:%{_datadir}/pkgconfig

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
mkdir -p $RPM_BUILD_ROOT%{_libdir}/pkgconfig
mkdir -p $RPM_BUILD_ROOT%{_datadir}/pkgconfig

# we include this below, already
rm -rf $RPM_BUILD_ROOT%{_datadir}/doc/pkg-config
# << install post


%files
%defattr(-,root,root,-)
# >> files
%doc AUTHORS README NEWS COPYING pkg-config-guide.html
%{_mandir}/*/*
%{_bindir}/*
%{_libdir}/pkgconfig
%{_datadir}/pkgconfig
%{_datadir}/aclocal/*
# << files
